import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Form | My UI Library',
  description: 'Generated by create next app',
}

type Props = {
  sideContent: React.ReactNode
  children: React.ReactNode
}

export default function PageLayout({ 
  sideContent,
  children 
}: Props) {
  return (
    <main className='min-h-screen flex gap-10 bg-slate-500'>
      <aside className='w-[300px] bg-white p-5 text-sm'>
        <Link href='/' className='underline mb-10 block'>Go back to Home Page</Link>

        { sideContent }
      </aside>
      
      <div className='flex-1 w-full flex items-center justify-center py-10'>
        <section className='w-full max-w-[600px] bg-white p-8 px-8 rounded-lg'>
          { children }
        </section>
      </div>
    </main>
  )
}

