import type { Metadata } from 'next'
import Link from 'next/link'
import PageLayout from '@/components/PageLayout'

export const metadata: Metadata = {
  title: 'Fetching | My UI Library',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ 
  children 
}: RootLayoutProps) {
  return (
    <PageLayout
      sideContent={
        <>
          <h2 className='mb-1'>Checklist:</h2>
          <ul className='mt-2 list-inside list-decimal flex flex-col gap-1'>
            <li>Handle Fetch Error</li>
            <li>Handle Code Error</li>
            <li>Handle jwt token</li>
            <li>Handle refetch</li>
          </ul>
          <hr className='my-10' />
          <h2 className='mb-1'>Fetch Strategies:</h2>
          <ol className='list-disc list-inside flex flex-col gap-1'>
            <li><Link href='/fetch/client-side' className='underline'>Client Side (React Query)</Link></li>
            <li><Link href='/fetch/server-side' className='underline'>Fetching in Server Side</Link></li>
            <li><Link href='/fetch/redux-static-data' className='underline'>Get Static Data (RTK)</Link></li>
            <li><Link href='/fetch/redux-toolkit' className='underline'>TODO (RTK)</Link></li>
          </ol>
        </>
      }
    >
      { children }
    </PageLayout>
  )
}

