import type { Metadata } from "next";
import "../globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import AppContextProvider from './shared/context'
import { auth } from "@/auth"
import PageLayout from '@/components/PageLayout'
import Menu from './shared/Menu'

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "System",
  description: "Generated by create next app",
}

type RootLayoutProps = {
  children: React.ReactNode
}

export default async function RootLayout({ 
  children 
}: RootLayoutProps) {
  const session: any = await auth()

  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <AppContextProvider session={session}>
          <PageLayout
            sideContent={
              <>
                <h2 className='mb-1'>Checklist:</h2>
                <ul className='mt-2 list-inside list-decimal flex flex-col gap-1'>
                  <li>Handle Fetch Error</li>
                  <li>Handle Code Error</li>
                  <li>Handle jwt token</li>
                  <li>Handle refetch</li>
                </ul>
                <hr className='my-5' />
                <Menu />
              </>
            }
          >
            { children }
          </PageLayout>
        </AppContextProvider>
      </body>
    </html>
  )
}

