import type { Metadata } from "next";
import "../globals.css";
import { Roboto } from "next/font/google"
import { cn } from "@/lib/utils"
import { ConfirmServiceProvider } from '@/hooks/useModalConfirm'

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "My UI Library",
  description: "Generated by create next app",
}

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ 
  children 
}: RootLayoutProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        // className={
        //   roboto.className
        // }
        className={cn(
          roboto.className,
          'min-h-screen bg-background'
        )}
      >
        <ConfirmServiceProvider>
          {children}
        </ConfirmServiceProvider>
      </body>
    </html>
  )
}

  